### ISSUE TITLE
LSP-Stylelint Blocking LSP-CSS autocompletions

### ISSUE THREAD

**Issue by dwhenson** [sublimelsp/LSP-stylelint#11]
Hi 

I'm using LSP-CSS for autocompletions and LSP-Stylelint for linting. However, when I enable LSP it immediately blocks LSP-CSS from autocompleting. When I disable Stylelint it LSP-CSS works again. Can you advise how to make these two LSPs work well together?

Thanks in advance.

**Comment by dwhenson** [comment]
Adding "priority_selector": "source.xxx" in **LSP-stylelint settings** seems to fix this but I'll leave the issue open for the moment as this is a hack, and I'm not sure how permanent this solution is.

**Comment by rchl** [comment]
I'm honestly not sure what a proper fix would be and where it should be made.

Since it's a problem with a conflict between two similar servers I'm not sure whether the choice should be made by the user which one is more important or we should explicitly set empty `priority_selector` here and force this one to have lower priority than any other server.

**Comment by predragnikolic** [comment]
We should probably send the completion request to all servers who have the completionProvider capability, await the results, parse them and combine them to a Sublime.CompletionList. (keeping in mind that one sever might return a list and another server might return an object that has `{isIncomplete: false, items[]}`, and a third server returning `{isIncomple: true, items:[]}`)
